name: Run app.py on schedule

on:
  schedule:
    - cron: '30 2 * * *' # Runs every day at 8:00 AM IST (2:30 AM UTC)
  workflow_dispatch:

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run app.py
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python app.py

      - name: Set up authenticated git remote
        if: success()
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.SAMAN_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit and push new extracted files
        if: success()
        run: |
          git config user.name "${{ github.actor }}"
          git config --global user.email mdsamanngp@gmail.com
          git add extract/*.csv
          if git diff --cached --quiet; then
            echo "No new files to commit."
          else
            git commit -m "Add new extracted emails file [skip ci]"
            git push
          fi
